name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "master"
  push:

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    env:
      SYMFONY_REQUIRE: "${{ matrix.symfony-version }}"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
        symfony-version:
          - "4.4.x"
          - "5.4.x"
          - "6.0.x"
          - "7.0.x"
        dependencies:
          - "highest"
        include:
          - dependencies: "lowest"
            php-version: "7.2"
            symfony-version: "4.4.*"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "composer:v2,flex"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit"
